services:
  db:
    image: postgres:15-alpine
    container_name: uca_db
    restart: always
    environment:
      POSTGRES_USER: uca_admin
      POSTGRES_PASSWORD: uca_password
      POSTGRES_DB: uca_game
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
